main/urls.py
from django.urls import path
from main.views import show_main, create_product, add_product_ajax 
from main.views import show_xml, show_json, show_xml_by_id, show_json_by_id
from main.views import edit_product, delete_product
from main.views import register, login_user, logout_user

app_name = 'main'

urlpatterns = [
    path('', show_main, name='show_main'),
    path('create-product', create_product, name='create_product'),
    path('xml/', show_xml, name='show_xml'),
    path('json/', show_json, name='show_json'),
    path('xml/<str:id>/', show_xml_by_id, name='show_xml_by_id'),
    path('json/<str:id>/', show_json_by_id, name='show_json_by_id'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('edit-product/<uuid:id>', edit_product, name='edit_product'),
    path('delete/<uuid:id>', delete_product, name='delete_product'),
    path('create-product-ajax', add_product_ajax, name='add_product_ajax'),
]

valo_trade/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User
import uuid  # tambahkan baris ini di paling atas

# Create your models here.
class Product(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)  # tambahkan baris ini
    time = models.DateField(auto_now_add=True)
    
    name = models.CharField(max_length=255)
    price = models.IntegerField()
    description = models.TextField()

main/forms.py
from django.forms import ModelForm
from main.models import Product
from django.utils.html import strip_tags

class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description"]
        
    def clean_name(self):
        name = self.cleaned_data["name"]
        return strip_tags(name)

    def clean_description(self):
        description = self.cleaned_data["description"]
        return strip_tags(description)

main/views.py
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.core import serializers
from main.forms import ProductForm
from main.models import Product
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.utils.html import strip_tags

# Create your views here.
@login_required(login_url='/login')
def show_main(request):
    # products = Product.objects.all()
    # products = Product.objects.filter(user=request.user)
    
    context = {
        'app_name' : 'Valorant Trade',
        'name': request.user.username,
        'npm' : '2306228390',
        'class': 'PBP F',
        'username': 'Furizou#9999',
        # 'products': products,
        'last_login': request.COOKIES['last_login'],
    }

    return render(request, "main.html", context)

def create_product(request):
    form = ProductForm(request.POST or None)
    
    if form.is_valid() and request.method == "POST":
        # form.save()
        product = form.save(commit=False)
        product.user = request.user
        product.save()
        return redirect('main:show_main')
    
    context = {'form': form}
    return render(request, "create_product.html", context)

@csrf_exempt
@require_POST
def add_product_ajax(request):
    name = strip_tags(request.POST.get("name"))
    price = strip_tags(request.POST.get("price"))
    description = request.POST.get("description")
    user = request.user
    
    new_product = Product(name=name, price=price, description=description, user=user)
    new_product.save()
    
    return HttpResponse(b"CREATED", status=201)

def edit_product(request, id):
    # Get product based on id
    product = Product.objects.get(pk=id)
    
    # Set product as the instance of form
    form = ProductForm(request.POST or None, instance=product)
    
    if form.is_valid() and request.method == "POST":
        # Save form & go back to home page (main)
        form.save()
        return HttpResponseRedirect(reverse('main:show_main'))
    
    context = {'form': form}
    return render(request, 'edit_product.html', context)

def delete_product(request, id):
    # Get product based on id
    product = Product.objects.get(pk = id)
    
    # Detelete the product
    product.delete()
    
    return HttpResponseRedirect(reverse('main:show_main'))

def show_xml(request):
    # data = Product.objects.all()
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json(request):
    # data = Product.objects.all()
    data = Product.objects.filter(user=request.user)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def show_xml_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("xml", data), content_type="application/xml")

def show_json_by_id(request, id):
    data = Product.objects.filter(pk=id)
    return HttpResponse(serializers.serialize("json", data), content_type="application/json")

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('main:login')
    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        if form.is_valid():
            user = form.get_user()
            login(request, user)
            response = HttpResponseRedirect(reverse("main:show_main"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.error(request, "Invalid username or password. Please try again.")

    else:
        form = AuthenticationForm(request)
    context = {'form': form}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('main:login'))
    response.delete_cookie('last_login')
    return response

main/templates/card_info.html
<div class="bg-red-500 rounded-xl overflow-hidden border-2 border-red-600"></div>
    <div class="p-4 animate-shine">
      <h5 class="text-lg font-dinnext-heavy text-white">{{ title }}</h5>
      <p class="text-white">{{ value }}</p>
    </div>
</div>

main/templates/card_product.html
<div class="relative break-inside-avoid">
    <div class="relative top-5 bg-gray-900 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-grey-900 transform rotate-0 hover:rotate-1 transition-transform duration-300">
        <div class="bg-red-500 text-gray-800 p-4 rounded-t-lg border-b-2 border-white">
            <h3 class="font-bold text-xl text-white mb-2">{{product.name}}</h3>
            <p class="text-gray-200">{{product.time}}</p>
        </div>


        <div class="p-4">
            <p class="font-dinnext-bold uppercase text-base text-red-500 mb-2">Description</p> 
            <p class="text-gray-200 mb-2">
                <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px),#374151_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1">{{product.description}}</span>
            </p>
            <div class="mt-4">
                
            </div>
        </div>
    </div>

    <div class="absolute top-1 right-4 flex space-x-1">
        <a href="{% url 'main:edit_product' product.pk %}" class="bg-gray-900 hover:bg-gray-500 text-white rounded-full p-2 transition duration-300 shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
        </a>
        <a href="{% url 'main:delete_product' product.pk %}" class="bg-gray-900 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
            </svg>
        </a>
    </div>


</div>

main/templates/login.html
{% extends 'base.html' %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
{% load static %}
<div class="min-h-screen flex items-center justify-center w-screen bg-gray-900 py-12 px-4 sm:px-6 lg:px-8">
  <div class="max-w-md w-full space-y-8">
    <div class="text-center">
      <img src="{% static 'images/logo_2.svg' %}" alt="Valorant Logo" class="h-20 w-20 mx-auto">
      <h2 class="mt-6 text-center text-3xl font-dinnext-heavy text-white">
        LOGIN TO YOUR ACCOUNT
      </h2>
    </div>
    <form class="mt-8 space-y-6" method="POST" action="">
      {% csrf_token %}
      <input type="hidden" name="remember" value="true">
      <div class="rounded-md shadow-sm -space-y-px">
        <div>
          <label for="username" class="sr-only">Username</label>
          <input id="username" name="username" type="text" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-t-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Username">
        </div>
        <div>
          <label for="password" class="sr-only">Password</label>
          <input id="password" name="password" type="password" required class="appearance-none rounded-none relative block w-full px-3 py-2 border border-gray-300 placeholder-gray-500 text-gray-900 rounded-b-md focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 focus:z-10 sm:text-sm" placeholder="Password">
        </div>
      </div>

      <div>
        <button type="submit" class="group relative w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-red-500 hover:bg-red-600 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500">
          Sign in
        </button>
      </div>
    </form>

    {% if messages %}
    <div class="mt-4">
      {% for message in messages %}
      {% if message.tags == "success" %}
            <div class="bg-green-100 border border-green-400 text-green-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% elif message.tags == "error" %}
            <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% else %}
            <div class="bg-blue-100 border border-blue-400 text-blue-700 px-4 py-3 rounded relative" role="alert">
                <span class="block sm:inline">{{ message }}</span>
            </div>
        {% endif %}
      {% endfor %}
    </div>
    {% endif %}

    <div class="text-center mt-4">
      <p class="text-sm text-white">
        Don't have an account yet?
        <a href="{% url 'main:register' %}" class="font-medium text-red-500 hover:text-red-600">
          Register Now
        </a>
      </p>
    </div>
  </div>
</div>
{% endblock content %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>Valorant Trade</title>

<script src="https://cdn.jsdelivr.net/npm/dompurify@3.1.7/dist/purify.min.js"></script>
{% endblock meta %}

{% block content %}
{% include 'navbar.html' %}
<div class="overflow-x-hidden px-4 md:px-8 pb-8 pt-24 min-h-screen bg-gray-100 flex flex-col">
  
  <!-- This is the user logged-in status -->  
  <div class="flex flex-col sm:flex-row sm:flex-wrap justify-between items-center mx-8 px-8 py-4 bg-gray-900 shadow-xl rounded-lg">
    
    <!-- These are nama and npm -->
    <div class="flex flex-row items-center sm:w-auto px-2 border-gray-500">

      <div class="flex flex-col pr-8 border-r-2 sm:pr-4">
        <h3 class="text-left text-lg sm:text-xl font-dinnext-heavy text-white uppercase">
          {{ name }}
        </h3>
        <h4 class="flex text-left font-dinnext-bold text-gray-100">{{ npm }}</h4>
      </div>

      <!-- Class Name -->
      <div class="flex items-center sm:ml-4 pl-4">
        <h3 class="text-left text-lg font-dinnext-heavy text-white">{{ class }}</h3>
      </div>
    </div>

    <!-- Last Login, aligned to the far right -->
    <div class="flex mt-4 sm:mt-0 sm:ml-auto items-center bg-white px-4 sm:px-8 h-8 rounded-lg">
      <h3 class="text-gray-900 text-center text-sm sm:text-base whitespace-nowrap">Last Login: {{ last_login }}</h3>
    </div>    

  </div>

  <div class="flex justify-end mb-6">
    <a href="{% url 'main:create_product' %}" class="bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 mt-5 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-103">
      Add New Product
    </a>
    <button data-modal-target="crudModal" data-modal-toggle="crudModal" 
      class="btn bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 mx-8 mt-5 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-103" 
      onclick="showModal();">
    <!-- <button data-modal-target="crudModal" data-modal-toggle="crudModal" class="btn bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-lg transition duration-300 ease-in-out transform hover:-translate-y-1 hover:scale-105" onclick="showModal();"> -->
      Add New Product by AJAX
    </button>
  </div>

  <div id="product_cards"></div>

  <div id="crudModal" tabindex="-1" aria-hidden="true" class="hidden fixed inset-0 z-50 w-full flex items-center justify-center bg-gray-800 bg-opacity-50 overflow-x-hidden overflow-y-auto transition-opacity duration-300 ease-out">
    <div id="crudModalContent" class="relative bg-white rounded-lg shadow-lg w-5/6 sm:w-3/4 md:w-1/2 lg:w-1/3 mx-4 sm:mx-0 transform scale-95 opacity-0 transition-transform transition-opacity duration-300 ease-out">
      <!-- Modal header -->
      <div class="flex items-center justify-between p-4 border-b rounded-t">
        <h3 class="text-xl font-semibold text-gray-900">
          Add New Product
        </h3>
        <button type="button" class="text-gray-400 bg-transparent hover:bg-gray-200 hover:text-gray-900 rounded-lg text-sm p-1.5 ml-auto inline-flex items-center" id="closeModalBtn">
          <svg aria-hidden="true" class="w-5 h-5" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg">
            <path fill-rule="evenodd" d="M4.293 4.293a1 1 0 011.414 0L10 8.586l4.293-4.293a1 1 0 111.414 1.414L11.414 10l4.293 4.293a1 1 0 01-1.414 1.414L10 11.414l-4.293 4.293a1 1 0 01-1.414-1.414L8.586 10 4.293 5.707a1 1 0 010-1.414z" clip-rule="evenodd"></path>
          </svg>
          <span class="sr-only">Close modal</span>
        </button>
      </div>
      <!-- Modal body -->
      <div class="px-6 py-4 space-y-6 form-style">
        <form id="productForm">
          <div class="mb-4">
            <label for="name" class="block text-sm font-medium text-gray-700">Name</label>
            <input type="text" id="name" name="name" 
              class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-red-700" 
              placeholder="Enter account username" required>
          </div>
          <div class="mb-4">
            <label for="price" class="block text-sm font-medium text-gray-700">Price</label>
            <input type="number" id="price" name="price" min="0" 
              class="mt-1 block w-full border border-gray-300 rounded-md p-2 hover:border-red-700" required>
          </div>
          <div class="mb-4">
            <label for="description" class="block text-sm font-medium text-gray-700">Account Description</label>
            <textarea id="description" name="description" rows="3" 
              class="mt-1 block w-full h-52 resize-none border border-gray-300 rounded-md p-2 hover:border-red-700" 
              placeholder="Describe your account specification" required></textarea>
          </div>
        </form>
      </div>
      <!-- Modal footer -->
      <div class="flex flex-col space-y-2 md:flex-row md:space-y-0 md:space-x-2 p-6 border-t border-gray-200 rounded-b justify-center md:justify-end">
        <button type="button" class="bg-gray-900 hover:bg-gray-700 text-white font-bold py-2 px-4 rounded-lg" id="cancelButton">Cancel</button>
        <button type="submit" id="submitMoodEntry" form="productForm" class="bg-red-700 hover:bg-red-600 text-white font-bold py-2 px-4 rounded-lg">Save</button>
      </div>
    </div>
  </div>

  <!-- {% if not products %}
  <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
      <img id="randomErrorImage" alt="Stupid Agents" class="w-32 h-32 mb-4"/>
      <p class="text-center text-gray-600 mt-4">Tidak ada akun valorant yang tersedia di Valorant Trade saat ini</p>
  </div>
  {% else %}

  <div class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 w-full max-w-[calc(100%-4rem)] mx-auto my-8">
    {% for product in products %}
        {% include 'card_product.html' with product=product %}
    {% endfor %}
  </div>
  {% endif %} -->
</div>

<script>
  // Array of image URLs
  const images = [
    "{% static 'images/error_face/breach.png' %}",
    "{% static 'images/error_face/gekko.png' %}",
    "{% static 'images/error_face/killjoy.png' %}",
    "{% static 'images/error_face/phoenix.png' %}",
    "{% static 'images/error_face/sova.png' %}"
  ];

  async function getProducts() {
    return fetch("{% url 'main:show_json' %}").then((res) => res.json())
  }

  async function refreshProducts() {
    document.getElementById("product_cards").innerHTML = "";
    document.getElementById("product_cards").className = "";
    const products = await getProducts();
    let htmlString = "";
    let classNameString = "";

    if (products.length === 0) {
      // Select a random image
      const randomImage = images[Math.floor(Math.random() * images.length)];

      classNameString = "flex flex-col items-center justify-center min-h-[24rem] p-6";
      htmlString = `
        <div class="flex flex-col items-center justify-center min-h-[24rem] p-6">
          <img id="randomErrorImage" src="${randomImage}" alt="Stupid Agents" class="w-32 h-32 mb-4"/>
          <p class="text-center text-gray-600 mt-4">Tidak ada akun valorant yang tersedia di Valorant Trade saat ini</p>
        </div>
      `;
    }
    else {
      classNameString = "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 w-full max-w-[calc(100%-4rem)] mx-auto my-8";
      products.forEach((item) => {
        const name = DOMPurify.sanitize(item.fields.name);
        const description = DOMPurify.sanitize(item.fields.description);

        htmlString += `
          <div class="relative break-inside-avoid">
            <div class="relative top-5 bg-gray-900 shadow-md rounded-lg mb-6 break-inside-avoid flex flex-col border-2 border-grey-900 transform rotate-0 hover:rotate-1 transition-transform duration-300">
              <div class="bg-red-500 text-gray-800 p-4 rounded-t-lg border-b-2 border-white">
                <h3 class="font-bold text-xl text-white mb-2">${item.fields.name}</h3>
                <p class="text-gray-200">${item.fields.time}</p>
              </div>

              <div class="p-4">
                <p class="font-dinnext-bold uppercase text-base text-red-500 mb-2">Description</p> 
                <p class="text-gray-200 mb-2">
                    <span class="bg-[linear-gradient(to_bottom,transparent_0%,transparent_calc(100%_-_1px),#374151_calc(100%_-_1px))] bg-[length:100%_1.5rem] pb-1">${item.fields.description}</span>
                </p>
                <div class="mt-4">
                    
                </div>
              </div>
            </div>

            <div class="absolute top-1 right-4 flex space-x-1">
              <a href="/edit-product/${item.pk}" class="bg-gray-900 hover:bg-gray-500 text-white rounded-full p-2 transition duration-300 shadow-md">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
                </svg>
              </a>
              <a href="/delete/${item.pk}" class="bg-gray-900 hover:bg-red-600 text-white rounded-full p-2 transition duration-300 shadow-md">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                  <path fill-rule="evenodd" d="M9 2a1 1 0 00-.894.553L7.382 4H4a1 1 0 000 2v10a2 2 0 002 2h8a2 2 0 002-2V6a1 1 0 100-2h-3.382l-.724-1.447A1 1 0 0011 2H9zM7 8a1 1 0 012 0v6a1 1 0 11-2 0V8zm5-1a1 1 0 00-1 1v6a1 1 0 102 0V8a1 1 0 00-1-1z" clip-rule="evenodd" />
                </svg>
              </a>
            </div>
          </div>
        `;
      });
    }
    document.getElementById("product_cards").className = classNameString;
    document.getElementById("product_cards").innerHTML = htmlString;
  }

  const modal = document.getElementById('crudModal');
  const modalContent = document.getElementById('crudModalContent');

  function showModal() {
    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    modal.classList.remove('hidden'); 
    setTimeout(() => {
      modalContent.classList.remove('opacity-0', 'scale-95');
      modalContent.classList.add('opacity-100', 'scale-100');
    }, 50); 
  }

  function hideModal() {
    // console.log("hideModal is triggered");  // Check if this logs when the button is clicked
    const modal = document.getElementById('crudModal');
    const modalContent = document.getElementById('crudModalContent');

    modalContent.classList.remove('opacity-100', 'scale-100');
    modalContent.classList.add('opacity-0', 'scale-95');

    setTimeout(() => {
      modal.classList.add('hidden');
    }, 150); 
  }

  function addProduct() {
    fetch("{% url 'main:add_product_ajax' %}", {
      method: "POST",
      body: new FormData(document.querySelector('#productForm')),
    })
    .then(response => refreshProducts())

    document.getElementById("productForm").reset();
    // document.querySelector("[data-modal-toggle='crudModal']").click(); 
    hideModal();

    return false;
  }

  document.getElementById("cancelButton").addEventListener("click", hideModal);
  document.getElementById("closeModalBtn").addEventListener("click", hideModal);
  document.getElementById("productForm").addEventListener("submit", (e) => {
    e.preventDefault();
    addProduct();
  })
  refreshProducts();
</script>

{% endblock content %}

main/templates/navbar.html
{% load static %}
<nav class="bg-gray-900 shadow-lg fixed top-0 left-0 z-40 w-screen">

  <!-- <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"> -->
  <div class="mx-auto md:mx-8 px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">

      <!-- Menu links -->
      <div class="flex items-center">
        <img src="{% static 'images/logo_2.svg' %}" alt="Valorant Logo" class="h-10 w-10 mr-3">
        <h1 class="text-2xl font-bold text-center text-white font-valorant" style="margin-bottom: -0.2em;">
          Valorant Trade
        </h1>

        <div class="hidden md:flex flex ml-8 space-x-2">
          <a href="{% url 'main:show_main' %}" class="text-lg font-bold text-center text-gray-300 hover:bg-gray-800 font-bold py-2 px-4 rounded transition duration-300">
            Home
          </a>

          <a href="{% url 'main:show_main' %}" class="text-lg font-bold text-center text-gray-300 hover:bg-gray-800 font-bold py-2 px-4 rounded transition duration-300">
            Products
          </a>

          <a href="{% url 'main:show_main' %}" class="text-lg font-bold text-center text-gray-300 hover:bg-gray-800 font-bold py-2 px-4 rounded transition duration-300">
            Cart
          </a>
        </div>
      </div>

      <!-- User Logged In -->
      <div class="hidden md:flex items-center">
        {% if user.is_authenticated %}
          <span class="text-gray-300 mr-4">Welcome, {{ user.username }}</span>
          <a href="{% url 'main:logout' %}" class="text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Logout
          </a>
        {% else %}
          <a href="{% url 'main:login' %}" class="text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mr-2">
            Login
          </a>
          <a href="{% url 'main:register' %}" class="text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
            Register
          </a>
        {% endif %}
      </div>

      <!-- Hidden menu -->
      <div class="md:hidden flex items-center">
        <button class="mobile-menu-button">
          <svg class="w-6 h-6 text-white" fill="none" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24" stroke="currentColor">
            <path d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </button>
      </div>
      
    </div>
  </div>

  <!-- Mobile menu -->
  <div class="mobile-menu hidden md:hidden  px-4 w-full md:max-w-full">
    <div class="pt-2 pb-3 space-y-1 mx-auto">

      <a href="{% url 'main:show_main' %}" class="block text-lg font-bold text-left text-gray-300 hover:bg-gray-800 py-2 px-4 rounded transition duration-300">
        Home
      </a>
      <a href="{% url 'main:show_main' %}" class="block text-lg font-bold text-left text-gray-300 hover:bg-gray-800 py-2 px-4 rounded transition duration-300">
        Products
      </a>
      <a href="{% url 'main:show_main' %}" class="block text-lg font-bold text-left text-gray-300 hover:bg-gray-800 py-2 px-4 rounded transition duration-300">
        Cart
      </a>
      
      {% if user.is_authenticated %}
        <span class="block text-gray-300 px-3 py-2">Welcome, {{ user.username }}</span>
        <a href="{% url 'main:logout' %}" class="block text-center bg-red-500 hover:bg-red-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Logout
        </a>
      {% else %}
        <a href="{% url 'main:login' %}" class="block text-center bg-blue-500 hover:bg-blue-600 text-white font-bold py-2 px-4 rounded transition duration-300 mb-2">
          Login
        </a>
        <a href="{% url 'main:register' %}" class="block text-center bg-green-500 hover:bg-green-600 text-white font-bold py-2 px-4 rounded transition duration-300">
          Register
        </a>
      {% endif %}
    </div>
  </div>
  <script>
    const btn = document.querySelector("button.mobile-menu-button");
    const menu = document.querySelector(".mobile-menu");
  
    btn.addEventListener("click", () => {
      menu.classList.toggle("hidden");
    });
  </script>
</nav>